### ISSUE TITLE
Paper or materials recommendedPaper or materials recommended

### ISSUE THREAD

**Issue by CTGUMARK** [robotics-upo/dynamic_obstacle_detector#3]
I would like to ask, what is the basic principle of the implementation of the function package? Do you have any relevant papers or materials to recommend? Thank you！

**Comment by noeperez** [comment]
Hello,

the ideas implemented here are very basic, so they are not based on any paper. 
We just perform a very very simple clustering of the points of the laser scan. Then, we discard some of the clusters based on the number of points. Finally, we use a Kalman Filter to track the clusters, so that we follow only the clusters (dynamic obstacles) that exceed a minimum-velocity threshold. 
If you are interested, you could take a look to different clustering algorithm that could be applied, and the theory behind Kalman Filters.
